# Generated by Django 3.2.7 on 2021-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='label',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
