# Generated by Django 3.2.7 on 2021-10-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_competition_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsubmission',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
