# Generated by Django 3.2.7 on 2021-10-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_competitionsubmission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='conditional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
