# Generated by Django 3.2.7 on 2021-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_competition_conditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='golden_file',
            field=models.FileField(blank=True, null=True, upload_to='scoring_program_file', verbose_name='golden'),
        ),
    ]
