# Generated by Django 3.2.7 on 2021-11-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_competition_golden_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='scoring_program_docker_image',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
