# Generated by Django 3.2.7 on 2021-11-15 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0006_competition_scoring_program_docker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ingestion_program',
            field=models.FileField(blank=True, null=True, upload_to='ingestion_program'),
        ),
        migrations.AddField(
            model_name='competition',
            name='ingestion_program_docker_image',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='OrganizerDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.TextField(default='')),
                ('type', models.CharField(choices=[('Reference Data', 'Reference Data'), ('Scoring Program', 'Scoring Program'), ('Input Data', 'Input Data'), ('Ingestion Program', 'Ingestion Program'), ('Starting Kit', 'Starting Kit'), ('Public Data', 'Public Data'), ('None', 'None')], default='None', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='dataset_data_file', verbose_name='Data file')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='ingestion_program_organizer_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_program_organizer_dataset', to='contest.organizerdataset'),
        ),
    ]
