# Generated by Django 3.2.7 on 2021-11-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20211115_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerdataset',
            name='sub_data_files',
            field=models.ManyToManyField(blank=True, null=True, to='contest.OrganizerDataSet', verbose_name='Bundle of data files'),
        ),
    ]
