# Generated by Django 3.2.7 on 2021-11-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_organizerdataset_sub_data_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='requirements',
            field=models.FileField(blank=True, default=None, null=True, upload_to='requirement'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='scoring_program_docker_image',
            field=models.FileField(blank=True, default=None, upload_to='dockerfiles'),
        ),
    ]
