# Generated by Django 3.2.7 on 2021-11-15 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_auto_20211115_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='scoring_program_docker_image',
            new_name='docker_config',
        ),
    ]
