# Generated by Django 3.2.7 on 2021-11-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_rename_scoring_program_docker_image_competition_docker_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSubmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('codename', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='requirements',
            field=models.FileField(blank=True, default=None, null=True, upload_to='requirement/%Y/%m/%d/'),
        ),
    ]
