# Generated by Django 3.2.7 on 2021-11-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20211118_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsubmission',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contest.competitionsubmissionstatus'),
        ),
    ]
