# Generated by Django 3.2.7 on 2021-11-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_alter_competitionsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsubmission',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.competitionsubmissionstatus'),
        ),
    ]
