# Generated by Django 3.2.7 on 2021-11-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_alter_competitionsubmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionsubmissionstatus',
            name='codename',
        ),
        migrations.AlterField(
            model_name='competitionsubmissionstatus',
            name='name',
            field=models.CharField(choices=[('submitting', 'submitting'), ('submitted', 'submitted'), ('running', 'running'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('None', 'None')], default='None', max_length=64),
        ),
    ]
