# Generated by Django 3.2.7 on 2021-11-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_auto_20211118_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='coopetition_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='detailed_results_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='history_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='prediction_stderr_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='prediction_stdout_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='private_output_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='runfile',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='status_details',
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='status',
            field=models.CharField(choices=[('submitting', 'submitting'), ('submitted', 'submitted'), ('running', 'running'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('None', 'None')], default='None', max_length=64),
        ),
        migrations.DeleteModel(
            name='CompetitionSubmissionStatus',
        ),
    ]
