# Generated by Django 3.2.7 on 2021-11-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_auto_20211118_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='coopetition_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='detailed_results_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='history_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='prediction_output_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='prediction_runfile',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='prediction_stderr_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='prediction_stdout_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='private_output_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='scores_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='status_details',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='stderr_file',
        ),
        migrations.RemoveField(
            model_name='competitionsubmission',
            name='stdout_file',
        ),
    ]
