# Generated by Django 3.2.7 on 2021-11-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0020_auto_20211118_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionSubmissionStatus',
        ),
        migrations.AddField(
            model_name='competitionsubmission',
            name='status',
            field=models.CharField(choices=[('submitting', 'submitting'), ('submitted', 'submitted'), ('running', 'running'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('None', 'None')], default='None', max_length=64),
        ),
    ]
