# Generated by Django 3.2.7 on 2021-11-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_auto_20211118_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, default=None, max_length=20, null=True)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('detail', 'detail'), ('participate', 'participate'), ('None', 'None')], default='None', max_length=64)),
                ('order', models.IntegerField(blank=True, default=None, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='contest.competition')),
            ],
        ),
    ]
