# Generated by Django 3.2.7 on 2021-12-15 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0023_auto_20211124_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='docker_config',
            field=models.FileField(blank=True, default=None, upload_to='dockerfiles/%Y%m%d/%h%m%s/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitioninfo_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competition',
            name='requirements',
            field=models.FileField(blank=True, default=None, null=True, upload_to='requirement/%Y%m%d/%h%m%s/'),
        ),
    ]
